"""Initial schema

Revision ID: b5eb2e59afd2
Revises: 
Create Date: 2026-09-24 17:22:50.840967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5eb2e59afd2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrator',
    sa.Column('admin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('admin_id')
    )
    with op.batch_alter_table('administrator', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_administrator_email'), ['email'], unique=True)

    op.create_table('student',
    sa.Column('student_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('cgpa', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('interests', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('student_id')
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_email'), ['email'], unique=True)

    op.create_table('opportunity',
    sa.Column('opportunity_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=150), nullable=False),
    sa.Column('min_cgpa', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('eligible_department', sa.String(length=100), nullable=True),
    sa.Column('eligible_level', sa.String(length=20), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['administrator.admin_id'], ),
    sa.PrimaryKeyConstraint('opportunity_id')
    )
    op.create_table('recommendation',
    sa.Column('recommendation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('similarity_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('eligibility_status', sa.Boolean(), nullable=False),
    sa.Column('eligibility_reason', sa.String(length=255), nullable=True),
    sa.Column('date_generated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.opportunity_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('recommendation_id'),
    sa.UniqueConstraint('student_id', 'opportunity_id', name='uq_student_opportunity')
    )
    with op.batch_alter_table('recommendation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendation_opportunity_id'), ['opportunity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_student_id'), ['student_id'], unique=False)

    op.create_table('notification',
    sa.Column('notification_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendation.recommendation_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_student_id'))

    op.drop_table('notification')
    with op.batch_alter_table('recommendation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_student_id'))
        batch_op.drop_index(batch_op.f('ix_recommendation_opportunity_id'))

    op.drop_table('recommendation')
    op.drop_table('opportunity')
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_email'))

    op.drop_table('student')
    with op.batch_alter_table('administrator', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_administrator_email'))

    op.drop_table('administrator')
    # ### end Alembic commands ###
